### ISSUE TITLE
digital_mpsk_receiver_cc is deprecated (removed in GnuRadio next)

### ISSUE THREAD

**Issue by pinkavaj** [bastibl/gr-rds#18]
This block is now deprecated and removed from next branch of GnuRadio. Is shuld be replaced by constellation_receiver.

For BPSK this C++ code snippet (1) replaces the deprecated block, for .grc corresponding blocks exists.

(1)
    gr::digital::constellation_sptr p_c = gr::digital::constellation_bpsk::make()->base();
    d_mpsk = gr::digital::constellation_receiver_cb::make(p_c, 1*M_PI/100.0, -0.06, 0.06);

**Comment by bastibl** [comment]
The next branch (which is supposed to be used with GNU Radio's next branch) should already have that updated.

**Comment by pinkavaj** [comment]
Sorry, i hooked only the main branch. I originaly posted it to GQRX and just wanted to point out this. You can close this issue if You did not want to change it in main.
