### ISSUE TITLE
not good work when i used hackrf

### ISSUE THREAD

**Issue by stackprogramer** [bastibl/gr-rds#19]
hi, your project is Great i used it with rtl-sdr. it work very good.
but when i used hackrf, it is poor result fm . the noise is so many. my question is how i can find a manual or reference for setting this blocks GRC gnuradio that work perfectly for hackrf. for input source i used hackrf,i changed parameter osmocom source very but quality is not good.
thank you
best regards stackprogramer

**Comment by bastibl** [comment]
Unfortunately, I don't have access to a HackRF, so I don't have any first hand experience. The most interesting parameter is certainly the gain, but I guess you already tried that.
Maybe you could post to the GNU Radio mailing list, there might be someone whs knows about some quirks when using the module with the HackRF.
