### ISSUE TITLE
gr_rds_decoder, parser, panel are missing. 

### ISSUE THREAD

**Issue by ziyuanjun** [bastibl/gr-rds#20]
I followed the README.md.
After the file rds_rx.grc loaded, i get these messages:
```
Block key "gr_rds_decoder" not found
Block key "gr_rds_panel" not found
Block key "gr_rds_parser" not found
```
Could anyone tell me what should i do to use these blocks.

![20170313_110042_5492n8t](https://cloud.githubusercontent.com/assets/10259127/23842703/2165ccb6-07f1-11e7-9e6c-4a9ea7403b68.png)

**Comment by bastibl** [comment]
I guess, you installed the blocks to a different directory and GRC doesn't know where the blocks are. Please adapt your `~/.gnuradio/config.conf` to include something like:

```
[grc]
global_blocks_path = /opt/local/share/gnuradio/grc/blocks
local_blocks_path = ~/usr/share/gnuradio/grc/blocks
```

**Comment by ziyuanjun** [comment]
Thank you very much!  It works!
ps: Maybe due to the version i installed is _GNU Radio Companion 3.7.10_, my configure file is `~/.gnuradio/grc.conf`.

**Comment by bastibl** [comment]
great!
