### ISSUE TITLE
Use of version tags

### ISSUE THREAD

**Issue by ajd394** [bastibl/gr-rds#22]
Have you considered the use of git tags to keep versions of the code? This would help with configuration management.

**Comment by bastibl** [comment]
No, I didn't. But if that's useful, I'd happy to add them. Since there is not much development going on with this module, I could, for example,  tag the current `master` as 1.0.0 and increase the last digid per commit.
Would that be helpful?

**Comment by ajd394** [comment]
yes that would be great! Thanks!
