### ISSUE TITLE
Please add support for gnuradio-3.9

### ISSUE THREAD

**Issue by yarda** [bastibl/gr-rds#41]
Gnuradio 3.9 is stable. It drops swig and uses pybind, so OOTs needs some changes. There is porting guide https://wiki.gnuradio.org/index.php/GNU_Radio_3.9_OOT_Module_Porting_Guide

We are trying to rebase gnuradio to 3.9 in Fedora Rawhide.

**Comment by yarda** [comment]
We used the following patch in Fedora downstream:
https://src.fedoraproject.org/rpms/gr-rds/blob/ad60e6e2b55757d6ffb47cc35dea85eb960fd100/f/gr-rds-1.1.0-gnuradio39.patch
It's untested and absolutely without any warranty :).

**Comment by elafargue** [comment]
There was still a bit of work to make it actually functional, but I just opened https://github.com/bastibl/gr-rds/pull/42 which ports gr-rds to GR 3.9, feedback appreciated.

**Comment by bastibl** [comment]
I just merged @elafargue's PR. There is now also a maint-3.9 branch. Please, let me know if there are any issues.
