### ISSUE TITLE
Failed to Load 'rds_rx.grc' example with RTL-SDR

### ISSUE THREAD

**Issue by CanBusHack** [bastibl/gr-rds#62]
Using gnuradio 3.10, the example loads but errors out when parsing and I receive the following error:

<<< Welcome to GNU Radio Companion v3.10-compat-xxx-xunknown >>>

Block paths:
	/home/user/.grc_gnuradio
	/usr/share/gnuradio/grc/blocks
	/usr/local/share/gnuradio/grc/blocks

Loading: "/home/user/git/gr-rds/examples/rds_rx.grc"
>>> Done

Generating: '/home/user/git/gr-rds/examples/rds_rx.py'

Executing: /usr/bin/python3 -u /home/user/git/gr-rds/examples/rds_rx.py

gr-osmosdr 0.2.0.0 (0.2.0) gnuradio 3.8.1.0
built-in source types: file osmosdr fcd rtl rtl_tcp uhd miri hackrf bladerf rfspace airspy airspyhf soapy redpitaya freesrp 
[INFO] [UHD] linux; GNU C++ version 9.2.1 20200304; Boost_107100; UHD_3.15.0.0-2build5
[INFO] Using format CF32.

>>> Done (return code -11)

Generating: '/home/user/git/gr-rds/examples/rds_rx.py'

Executing: /usr/bin/python3 -u /home/user/git/gr-rds/examples/rds_rx.py

gr-osmosdr 0.2.0.0 (0.2.0) gnuradio 3.8.1.0
built-in source types: file osmosdr fcd rtl rtl_tcp uhd miri hackrf bladerf rfspace airspy airspyhf soapy redpitaya freesrp 
[INFO] [UHD] linux; GNU C++ version 9.2.1 20200304; Boost_107100; UHD_3.15.0.0-2build5
Found Rafael Micro R820T tuner
Using device #0 Realtek RTL2838UHIDIR SN: 00000001
Found Rafael Micro R820T tuner
[R82XX] PLL not locked!
Exact sample rate is: 2000000.052982 Hz
[R82XX] PLL not locked!
Traceback (most recent call last):
  File "/home/user/git/gr-rds/examples/rds_rx.py", line 429, in <module>
    main()
  File "/home/user/git/gr-rds/examples/rds_rx.py", line 407, in main
    tb = top_block_cls()
  File "/home/user/git/gr-rds/examples/rds_rx.py", line 133, in __init__
    self.rds_parser_0 = rds.parser(False, False, 0)
AttributeError: module 'rds' has no attribute 'parser'

>>> Done (return code 1)

**Comment by bastibl** [comment]
Looks like you use GNU Radio 3.10 with gr-osmosdr compiled for GNU Radio 3.8. This won't work.
