### ISSUE TITLE
Fresh install failure

### ISSUE THREAD

**Issue by CanBusHack** [bastibl/gr-rds#64]
After doing a fresh install I receive a new error:

Python 3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import rds
Traceback (most recent call last):
  File "/usr/local/lib/python3/dist-packages/rds/__init__.py", line 17, in <module>
    from .bindings.rds_python import *
ModuleNotFoundError: No module named 'rds.bindings'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3/dist-packages/rds/__init__.py", line 19, in <module>
    from .rds_python import *
ImportError: generic_type: type "decoder" referenced unknown base type "gr::sync_block"

Using gnuradio version "v3.10-compat-xxx-xunknown"
Using SoapyRTLSDR: 
 Lib Version: v0.8.1-g9cbaa3cf
 API Version: v0.8.0
 ABI Version: v0.8
Using gr-rds version: Unknown (built from maint-3.10)

Any help would be appreciated.

**Comment by bastibl** [comment]
I'm not sure what you are doing, but gr-rds should be in Ubuntu mainline repos. Can't you just use this?

**Comment by rapbando** [comment]
Same problem using soapySDRsource with Kali rolling and gr-rds installed from repository:

```
<<< Welcome to GNU Radio Companion 3.10.3.0 >>>

Block paths:
	/usr/share/gnuradio/grc/blocks
	/usr/local/share/gnuradio/grc/blocks

Loading: "/home/user/gr-rds-3.10/examples/rds_rx.grc"
>>> Done

Generating: '/home/user/gr-rds-3.10/examples/rds_rx.py'

Executing: /usr/bin/python3 -u /home/user/gr-rds-3.10/examples/rds_rx.py

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/rds/__init__.py", line 17, in <module>
    from .bindings.rds_python import *
ModuleNotFoundError: No module named 'rds.bindings'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/gr-rds-3.10/examples/rds_rx.py", line 43, in <module>
    import rds
  File "/usr/lib/python3/dist-packages/rds/__init__.py", line 19, in <module>
    from .rds_python import *
ImportError: generic_type: type "decoder" referenced unknown base type "gr::sync_block"

>>> Done (return code 1)
```

**Comment by bastibl** [comment]
This is an issue with packaging. Please contact the Ubuntu package maintainer.

**Comment by rapbando** [comment]
After trashing everything and cloning again the project and doing the exact same steps now SoapySDR source and sink works.
Maybe somehing got corrupted along the way
