### ISSUE TITLE
Stereo and Mono are swapped

### ISSUE THREAD

**Issue by Knorxi** [bastibl/gr-rds#65]
When I'm listening to a stereo station, the RDS Panel shows "Mono"
https://github.com/bastibl/gr-rds/blob/113b70bc0bfb8dccb2358d571ba64c0d2c90e9b4/lib/parser_impl.cc#L125
When I swap the '1' and '0' it works. But then the code doesn't look so good anymore ;-)
May be the variable should be renamed to stereo_mono ...

**Comment by argilo** [comment]
NRSC-4-A, which seems to be the only publicly available RDS standard, states:

> Bit d<sub>0</sub>, set to 0: Mono
 >Bit d<sub>0</sub>, set to 1: Stereo

So it would appear that line you quoted is correct, but the following lines are incorrect:

https://github.com/bastibl/gr-rds/blob/7af76878a7e4d3fd22e252d7f2ae5dde4106c30a/lib/parser_impl.cc#L166

https://github.com/bastibl/gr-rds/blob/7af76878a7e4d3fd22e252d7f2ae5dde4106c30a/python/rdspanel.py#L151-L156

**Comment by argilo** [comment]
Also of note: The abstract of [IEC 62106-2:2018](https://webstore.iec.ch/publication/60309) states that:

> Obsolete and no longer part of the RDS standard are: MS (Group 0A, 0B and 15B) certain DI codes (**mono/stereo**, artificial head, compression), Language code, and PIN (Group 1A).

So it seems that the field no longer exists in recent versions of the RDS standard.

**Comment by argilo** [comment]
I did a quick survey of my local stations. Most are broadcasting in stereo, but only one sets the "stereo" bit in RDS. Perhaps this is part of the reason why the field was removed in IEC 62106-2:2018.

**Comment by Knorxi** [comment]
Thanks for the response and the cool RDS code.
I can learn a lot from that.

I was going to say "I'm glad the standard has been withdrawn so that the stereo bit is preserved ;-)", but, I have also tested a few radio stations and in Germany some of them do not broadcast the stereo bit also.

Concerning the mono / stereo problem in parser_impl.cc:
You are right.
I have always a problem in variable names with the 2 states in the name.
In never know which state is "1".
E.g. there are the variables "music_speech" and "mono_stereo" in the code.
In the IEC for "Music" the bit is set and for "Speech" the bit is not set.
For "Stereo" another bit is set and the same bit is not set for "Mono".
So in the variable name "**music** _speech" is the state where the bit is set the first word.
But in "mono _**stereo**" is the state where the bit is set the second word.

**Comment by bastibl** [comment]
My 1999 copy of IEC 62106 agrees :-) I'll go ahead and merge the PR. Thank you!

![mono](https://user-images.githubusercontent.com/159628/182869219-5c899b8a-3e8d-49e2-b6ac-6a1045c3bac6.png)
