### ISSUE TITLE
Small comments to the great .grc examples

### ISSUE THREAD

**Issue by Brumi-2021** [bastibl/gr-rds#72]
Hello thanks a lot for sharing that gr-rds  and FM stereo ( rx / tx) . 
Great job,  it is the perfect reference that I was searching,  and also it works  with version gnuradio 3.10.6  ! 

Just let me add small comments to your examples, for your consideration , 
(1) [rds_rx.grc](https://github.com/bastibl/gr-rds/blob/maint-3.9/examples/rds_rx.grc)
Regarding that deemphasis block , as I am in EUR,   I would just add this comment ,
Tau : Time constant in seconds (75us in US, 50us in EUR)
![image](https://github.com/bastibl/gr-rds/assets/86470699/3d487988-f99e-40f6-8417-54828194f615)

(2) [rds_tx.grc](https://github.com/bastibl/gr-rds/blob/maint-3.9/examples/rds_tx.grc)
Here in that transmitter example , I would just add two comments ,

a-) I think it is missing to add in audio baseband , the two symetrical pre-emphasis filters , 
![image](https://github.com/bastibl/gr-rds/assets/86470699/4706f1ba-2074-4020-9830-d5bed1e2e20a)

b-) Regarding the modulation index level of each part ,  If I understood correctly , current grc is using 26% for (L+R) and (L-R),
![image](https://github.com/bastibl/gr-rds/assets/86470699/ceb89d2b-be03-4e69-91f4-a454f85b0988)
(but not sure if this is the right FM stereo specs) 

Then , based on that , my understanding is that in FM STEREO transmission,  
(L+R) baseband ,  and (L-R ) double sideband suppressed carrier (DSBSC) sub-channel , could be each one 42,5%,  
Pilot Tone 19Khz 10% , and RDS BPSK around  5% .

![image](https://github.com/bastibl/gr-rds/assets/86470699/4fa126e3-59bf-48fb-a314-575edbe2d047)

In that sense , I think we can increase that 0.26  to 0.425 , if I am not wrong . 

Feel free to close or modify that issue , if it is not completely correct, 

Cheers, and thanks for your great contribution to gnuradio community !!!

**Comment by bastibl** [comment]
Thank you very much for the issue and for the detailed comments. This sounds very reasonable to me. Would you mind opening a PR to incorporate these changes?

**Comment by Brumi-2021** [comment]
Ok , thanks , I will try to submit the related small PR to update accordingly those two GRC examples . 

BTW , two more small comments , in the current RDS receiver , I do not see two correct dots in the decoded BPSK constellation, I saw just an horizontal line , maybe it is my set up problem . 
And regarding the transmitter , I tried several different receivers . The stereo separation works very good ,  but I always can hear some very  small residual background audio noise there in both channels , not sure where it comes from , pending to investigate it . I tried to increase the RF signal but not related. Anyone had same issue ?

**Comment by bastibl** [comment]
Closed with https://github.com/bastibl/gr-rds/pull/73
