### ISSUE TITLE
Receiving TMC question

### ISSUE THREAD

**Issue by THuber2145** [bastibl/gr-rds#75]
Hello,

thanks for your awesome Project.

I have a question about receiving tmc messages, i have the latest version of your blocks and your rx example (grc 3.10) up and running with an RTL-SDR dongle. RDS works great!

I may be blind, but where can I see the output of the decoded tmc messages?
Sorry to bother you, keep up the good work!

**Comment by bastibl** [comment]
Hi, not all stations broadcast TMC message all the time. If TMC messages are decoded, the *RDS Parser* block should print them to standard out, if logging is enabled.
See here: https://github.com/bastibl/gr-rds/blob/maint-3.9/lib/parser_impl.cc#L405-L414 

You can enable logging in the options of the *RDS Parser* block and try different radio stations.

**Comment by THuber2145** [comment]
Hi, thanks for the  for the extremely quick response, 
I'll take a look at that parser block again!
