### ISSUE TITLE
Field order in RDSPanel

### ISSUE THREAD

**Issue by marshallartsoz** [bastibl/gr-rds#76]
This is all brilliant stuff, thanks so much for putting in the work, and for making it available. I have installed the maint-3.10 branch on my Linux Mint system, and it works great.  Just one odd thing I noted - in the window that comes up when I run the rds_rx.grc flow in the GnuRadio Companion, the fields for Program ID and Program Type seem to be the wrong way around.  I'm not a Python coder, but I had a look at the rdspanel.py code, and nothing hit me in the eye that looked wrong.  Not a big deal obviously, but I just like things to look right. I've attached a clip of a screenshot that shows what I mean.

![GR-RDS](https://github.com/bastibl/gr-rds/assets/33501761/86df5064-3176-459d-929b-f5e525bd4bfa)

**Comment by bastibl** [comment]
Can you please check, if you have the most recent version. It was changed here: https://github.com/bastibl/gr-rds/pull/71. Or is this another issue?

**Comment by marshallartsoz** [comment]
Thanks for the reply.  I only downloaded this a few days ago, and installed from the zipfile named gr-rds-maint-3.10.  Its modification date is later than issue #71, does that mean I have the right one?  Sorry, I'm not a big github user, so not strong on knowing my way around.

**Comment by bastibl** [comment]
Can you check the `rdspanel.py` file of your zip file, if it has the changes from #71? Maybe there is also an older gr-rds installation from your package manager (or similar) on your system, which also installed the RDS panel and this gets used when you start the flowgraph.

**Comment by marshallartsoz** [comment]
It does now.  Thanks.  I'm not exactly clear on what was happening there, but no matter, it's fine now.
