### ISSUE TITLE
RDS isn't generated/TEF6686 doesn't show RDS flag

### ISSUE THREAD

**Issue by gabba43** [bastibl/gr-rds#82]
Hi everyone, first off: Awesome project! I really appreciate your work. My hobby is rf engineering & fm broadcasting and I'm currently trying to build a link receiver and mpx (RDS+stereo) encoder on a Raspberry Pi 2 W or Orange Pi Zero 3.

Now the issue I faced: Your RDS encoder is not working. Tried it on a Linux Mint 12 desktop with a VCO-PLL-tx by PCS Electronics. My 384kHz Realtek sound card is not the issue as it works perfectly fine on the same system using Stereo Tool. 

Edit: I'm outputting the generated MPX to the sound card. It's definetely set to 192kHz.

Same on a Win10 machine with Airomate: The sound card does generate proper stereo & RDS.

Tried the branch for GnuRadio 3.9 as well as the new version for GnuRadio 3.10 - no luck. QT Frequency FFT shows a correctly generated 57kHz-RDS-subcarrier & 19kHz stereo pilot. Also, I get a sound output on that sound card in GnuRadio - but no RDS.

Checked everything using my Tef6686 - the RDS flag doesn't light up. When using StereoTool or Airomate, it does immediately.

Do you know what's the issue here? Maybe I made a mistake.

**Comment by bastibl** [comment]
Could you please upload the modified TX flowgraph some where please?

**Comment by gabba43** [comment]
Yes, of course. I basically only added the audio output, deleted the faulty piece before the RDS encoder and deleted the rf section in the end. I also found that I'm not the only one struggling with this: https://www.reddit.com/r/GNURadio/comments/uw9gla/transmitting_fm_rds_rbds_via_192khz_soundcard/

Here it is:
![rds not working](https://github.com/user-attachments/assets/17c23f12-9798-4653-9717-7b5c44955989)
[rds_tx_copy.grc.zip](https://github.com/user-attachments/files/17542472/rds_tx_copy.grc.zip)

**Comment by argilo** [comment]
The sample rate at the output of the Add block is 380 ksps, so you can't directly attach a 192 ksps Audio Sink and expect it to work. You would need to add a Rational Resampler block in between.

**Comment by argilo** [comment]
Interpolation 192, Decimation 380.

**Comment by gabba43** [comment]
Thank you very much for your fast reply! I'll give it a try.

**Comment by gabba43** [comment]
I'm jumping in circles with joy :D It works! You're a genius. When I finished my project with the Orange Pi, I'll tell you and post everything on Radionecks - of course crediting you!

**Comment by argilo** [comment]
I'm glad to hear it worked!
